# DevEnv - Mise Configuration
# Added by devenv

[tools]
# Example tool versions - uncomment as needed
# python = "3.11"
# node = "20"
# go = "1.21"

[env]
# Environment variables
# _.python.venv = { path = ".venv", create = true }
